name: Android Build
 
on:
 push:
  branches:
   - main
 
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
 
   - name: Set up ruby env
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 2.7.2
       bundler-cache: true
 
   - name: Decode Service Account Key JSON File
     uses: timheuer/base64-to-file@v1
     id: service_account_json_file
     with:
       fileName: "serviceAccount.json"
       encodedString: ${{ secrets.PLAY_CONSOLE_KEYS }}
       
   - name: Get Client Id
     env:
       MOCK_USERNAME: ${{ secrets.CLIENT_ID }}
     run: echo clientId="$CLIENT_ID" > ./local.properties

   - name: Get TMDB Client Id
     env:
       MOCK_USERNAME: ${{ secrets.TMDB_CLIENT_ID }}
     run: echo tmdbClientId="$TMDB_CLIENT_ID" > ./local.properties
  
   - name: Build App 
     run: bundle exec fastlane android build
 
   - name: Upload build artifacts
     uses: actions/upload-artifact@v2
     with:
       name: assets
       path: |
         ${{ github.workspace }}/app/build/outputs/bundle/release
