name: Android Build
 
on:
 push:
  branches:
   - main
 
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
 
   - name: Set up ruby env
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 2.7.2
       bundler-cache: true
 
   - name: Decode Service Account Key JSON File
     uses: timheuer/base64-to-file@v1
     id: service_account_json_file
     with:
       fileName: "serviceAccount.json"
       encodedString: ${{ secrets.PLAY_CONSOLE_KEYS }}
       
   - name: Decode IDS
     uses: timheuer/base64-to-file@v1
     id: local_properties
     with:
       fileName: "local.properties"
       encodedString: ${{ secrets.IDS }}
  
   - name: Build App 
     run: bundle exec fastlane android build
 
   - name: Upload build artifacts
     uses: actions/upload-artifact@v2
     with:
       name: assets
       path: |
         ${{ github.workspace }}/app/build/outputs/bundle/release
